# Generated by Django 5.2 on 2025-11-05 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.viaje'),
        ),
    ]
