# Generated by Django 5.1.7 on 2025-10-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
