# Generated by Django 5.1.7 on 2025-10-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0002_estado_activo_estado_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='descripcion',
        ),
    ]
