<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-10-12 14:51
=======
# Generated by Django 5.1.7 on 2025-09-22 23:36
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre', models.CharField(max_length=100, unique=True)),
=======
                ('nombre', models.CharField(max_length=100)),
>>>>>>> main
            ],
        ),
    ]
