# Generated by Django 5.0.2 on 2025-11-10 18:30

from django.db import migrations

def resave_data(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    for obj in Usuario.objects.all():
        obj.save()

    Provincia = apps.get_model('provincias', 'Provincia')
    for obj in Provincia.objects.all():
        obj.save()

    Localidad = apps.get_model('localidad', 'Localidad')
    for obj in Localidad.objects.all():
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('provincias', '0001_initial'),
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(resave_data),
    ]