# Generated by Django 5.2 on 2025-11-05 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localidad', '0003_localidad_lat_localidad_lon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('asientos_disponibles', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detalle_viaje', models.CharField(blank=True, max_length=200, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_creados', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_destino', to='localidad.localidad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_origen', to='localidad.localidad')),
            ],
        ),
    ]
