# Generated by Django 5.1.7 on 2025-10-06 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado', '0002_estado_activo_estado_descripcion'),
        ('provincias', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('asientos_disponibles', models.IntegerField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='usuarios.usuario')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_destino', to='provincias.provincia')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estado.estado')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_origen', to='provincias.provincia')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculo')),
            ],
        ),
    ]
