# Generated by Django 5.2 on 2025-11-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='CREADO', max_length=10),
        ),
    ]
