# Generated by Django 5.2 on 2025-10-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='detalle_viaje',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
