# Generated by Django 5.2.7 on 2025-10-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje_detalle_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
    ]
