# Generated by Django 5.2 on 2025-11-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='distancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
