# Generated by Django 5.2.7 on 2025-10-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_viaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('EN CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado')], default='CREADO', max_length=20),
        ),
    ]
