# Generated by Django 5.2 on 2025-10-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_alter_viaje_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='estado',
        ),
    ]
