# Generated by Django 5.2.7 on 2025-11-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
