# Generated by Django 5.1.7 on 2025-10-08 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
