# Generated by Django 5.0.2 on 2025-11-10 18:45

from django.db import migrations

def resave_data(apps, schema_editor):
    Vehiculo = apps.get_model('vehiculos', 'Vehiculo')
    for obj in Vehiculo.objects.all():
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_año'),
    ]

    operations = [
        migrations.RunPython(resave_data),
    ]