# Generated by Django 5.1.7 on 2025-10-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20251013_1749'),
        ('vehiculos', '0002_delete_vehiculo'),
    ]

    operations = [
    ]
