# Generated by Django 5.1.7 on 2025-10-13 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provincia',
            new_name='Localidad',
        ),
    ]
