# Generated by Django 5.2 on 2025-11-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0002_rename_provincia_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localidad',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
