# Generated by Django 5.2 on 2025-11-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localidad', '0004_alter_localidad_lat_alter_localidad_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
